runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://heroku_jk2jb9x2:n84fnp51qk6csd18rpjm46ajtu@ds119732.mlab.com:19732/heroku_jk2jb9x2
  APP_ID: final-jumble-id
  MASTER_KEY: final-jumble-key
  SERVER_URL: https://final-jumble.herokuapp.com/parse
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  
